### ISSUE TITLE
Feed doesn't update automatically

### ISSUE THREAD

**Issue by leandroprz** [splitbrain/patreon-rss#2]
I'm using this on a WordPress widget but the feed doesn't update automatically. I have to go to the PatreonRSS.php and the .xml files in order for the feed to get updated and show the current item on the widget.

Any idea what could be happening?

**Comment by splitbrain** [comment]
sorry but this is not enough information to work with. since the script is still working fine for me I assume there is something wrong with your WordPress thing.
