### ISSUE TITLE
Integrate into rss-bridge

### ISSUE THREAD

**Issue by josch** [splitbrain/patreon-rss#3]
Hi,

https://github.com/RSS-Bridge/rss-bridge is a php based web service offering RSS feeds for over 200 websites that do not offer one yet. But Patreon is missing. Maybe you would consider submitting a pull request to Rss-Bridge and continuing to maintain your code there?

Thanks!

cheers, josch

**Comment by splitbrain** [comment]
sorry, I have too much on my plate already. but feel free to use my code in any way you see fit.
